param(
    [string]$WebRoot = "",
    [string]$OutputFile = ""
)

$ErrorActionPreference = "Stop"
$ScriptDir = $PSScriptRoot
$RepoRoot = Split-Path $ScriptDir -Parent
if ([string]::IsNullOrEmpty($WebRoot)) {
    $WebRoot = Join-Path $RepoRoot "cnr-revived-web\maps\zombies"
}
if ([string]::IsNullOrEmpty($OutputFile)) {
    $OutputFile = Join-Path $RepoRoot "cnr-revived-web\mods\CNRMod\ZombieBuiltinContent.generated.cs"
}

$configDir = Join-Path $WebRoot "configs"
$assetDir = Join-Path $WebRoot "assets"

function To-B64([string]$text) {
    if ($null -eq $text) { $text = "" }
    return [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($text))
}

$configEntries = @()
if (Test-Path $configDir) {
    Get-ChildItem $configDir -File -Filter "*.json" | Sort-Object Name | ForEach-Object {
        $scene = [IO.Path]::GetFileNameWithoutExtension($_.Name)
        $raw = [IO.File]::ReadAllText($_.FullName)
        $configEntries += [PSCustomObject]@{ Key=$scene; B64=(To-B64 $raw) }
    }
}

$assetEntries = @()
if (Test-Path $assetDir) {
    Get-ChildItem $assetDir -File | Where-Object { $_.Extension -eq ".json" -or $_.Name.EndsWith(".cnrzobj.json", [StringComparison]::OrdinalIgnoreCase) } | Sort-Object Name | ForEach-Object {
        $raw = [IO.File]::ReadAllText($_.FullName)
        $assetEntries += [PSCustomObject]@{ Key=$_.Name; B64=(To-B64 $raw) }
    }
}

$sb = New-Object Text.StringBuilder
[void]$sb.AppendLine("// AUTO-GENERATED by APK_Build_Active/generate_zombie_builtin.ps1")
[void]$sb.AppendLine("// Do not hand-edit. Rebuild CNRMod to regenerate from maps/zombies/configs + assets.")
[void]$sb.AppendLine("using System;")
[void]$sb.AppendLine("using System.Collections.Generic;")
[void]$sb.AppendLine("using System.Text;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace CNRZombieMod")
[void]$sb.AppendLine("{")
[void]$sb.AppendLine("    internal static class ZombieBuiltinContent")
[void]$sb.AppendLine("    {")
[void]$sb.AppendLine("        private static readonly Dictionary<string, string> Maps = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)")
[void]$sb.AppendLine("        {")
foreach ($e in $configEntries) {
    [void]$sb.AppendLine(('            { "' + $e.Key.Replace('"','\"') + '", "' + $e.B64 + '" },'))
}
[void]$sb.AppendLine("        };")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("        private static readonly Dictionary<string, string> Assets = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)")
[void]$sb.AppendLine("        {")
foreach ($e in $assetEntries) {
    [void]$sb.AppendLine(('            { "' + $e.Key.Replace('"','\"') + '", "' + $e.B64 + '" },'))
}
[void]$sb.AppendLine("        };")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("        private static string Decode(string b64)")
[void]$sb.AppendLine("        {")
[void]$sb.AppendLine("            if (string.IsNullOrEmpty(b64)) return string.Empty;")
[void]$sb.AppendLine("            return Encoding.UTF8.GetString(Convert.FromBase64String(b64));")
[void]$sb.AppendLine("        }")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("        internal static bool TryGetMap(string scene, out string json)")
[void]$sb.AppendLine("        {")
[void]$sb.AppendLine("            json = null;")
[void]$sb.AppendLine("            string b64;")
[void]$sb.AppendLine("            if (string.IsNullOrEmpty(scene) || !Maps.TryGetValue(scene, out b64)) return false;")
[void]$sb.AppendLine("            json = Decode(b64);")
[void]$sb.AppendLine("            return !string.IsNullOrEmpty(json);")
[void]$sb.AppendLine("        }")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("        internal static bool TryGetAsset(string nameOrUrl, out string json)")
[void]$sb.AppendLine("        {")
[void]$sb.AppendLine("            json = null;")
[void]$sb.AppendLine("            if (string.IsNullOrEmpty(nameOrUrl)) return false;")
[void]$sb.AppendLine("            string key = nameOrUrl.Replace('\\', '/');")
[void]$sb.AppendLine("            int slash = key.LastIndexOf('/');")
[void]$sb.AppendLine("            if (slash >= 0) key = key.Substring(slash + 1);")
[void]$sb.AppendLine("            string b64;")
[void]$sb.AppendLine("            if (!Assets.TryGetValue(key, out b64)) return false;")
[void]$sb.AppendLine("            json = Decode(b64);")
[void]$sb.AppendLine("            return !string.IsNullOrEmpty(json);")
[void]$sb.AppendLine("        }")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("        internal static int MapCount { get { return Maps.Count; } }")
[void]$sb.AppendLine("        internal static int AssetCount { get { return Assets.Count; } }")
[void]$sb.AppendLine("    }")
[void]$sb.AppendLine("}")

[IO.File]::WriteAllText($OutputFile, $sb.ToString(), (New-Object Text.UTF8Encoding($false)))
Write-Host ("Zombie built-in content generated: {0} map(s), {1} asset(s) -> {2}" -f $configEntries.Count, $assetEntries.Count, $OutputFile) -ForegroundColor Cyan
